from distutils.core import setup

setup(
    name='ppedit',
    version='1.0.0',
    packages=['env.lib.python3.5.site-packages.pip', 'env.lib.python3.5.site-packages.pip.req',
              'env.lib.python3.5.site-packages.pip.vcs', 'env.lib.python3.5.site-packages.pip.utils',
              'env.lib.python3.5.site-packages.pip.compat', 'env.lib.python3.5.site-packages.pip.models',
              'env.lib.python3.5.site-packages.pip._vendor', 'env.lib.python3.5.site-packages.pip._vendor.distlib',
              'env.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.5.site-packages.pip._vendor.colorama',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.trie',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.serializer',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.5.site-packages.pip._vendor.lockfile',
              'env.lib.python3.5.site-packages.pip._vendor.progress',
              'env.lib.python3.5.site-packages.pip._vendor.requests',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.5.site-packages.pip._vendor.packaging',
              'env.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.5.site-packages.pip.commands', 'env.lib.python3.5.site-packages.pip.operations',
              'env.lib.python3.5.site-packages.enki', 'env.lib.python3.5.site-packages.enki.lib',
              'env.lib.python3.5.site-packages.enki.core', 'env.lib.python3.5.site-packages.enki.plugins',
              'env.lib.python3.5.site-packages.enki.plugins.lint', 'env.lib.python3.5.site-packages.enki.plugins.repl',
              'env.lib.python3.5.site-packages.enki.plugins.preview',
              'env.lib.python3.5.site-packages.enki.plugins.helpmenu',
              'env.lib.python3.5.site-packages.enki.plugins.vimtutor',
              'env.lib.python3.5.site-packages.enki.plugins.fuzzyopen',
              'env.lib.python3.5.site-packages.enki.plugins.navigator',
              'env.lib.python3.5.site-packages.enki.plugins.appshortcuts',
              'env.lib.python3.5.site-packages.enki.plugins.editortoolbar',
              'env.lib.python3.5.site-packages.enki.plugins.qpartsettings',
              'env.lib.python3.5.site-packages.enki.plugins.searchreplace',
              'env.lib.python3.5.site-packages.enki.widgets', 'env.lib.python3.5.site-packages.enki.resources',
              'env.lib.python3.5.site-packages.PyQt5', 'env.lib.python3.5.site-packages.PyQt5.uic',
              'env.lib.python3.5.site-packages.PyQt5.uic.Loader', 'env.lib.python3.5.site-packages.PyQt5.uic.port_v2',
              'env.lib.python3.5.site-packages.PyQt5.uic.port_v3', 'env.lib.python3.5.site-packages.PyQt5.uic.Compiler',
              'env.lib.python3.5.site-packages.qutepart', 'env.lib.python3.5.site-packages.qutepart.syntax',
              'env.lib.python3.5.site-packages.qutepart.indenter',
              'env.lib.python3.5.site-packages.qutepart-3.0.1-py3.5-linux-x86_64.egg.qutepart',
              'env.lib.python3.5.site-packages.qutepart-3.0.1-py3.5-linux-x86_64.egg.qutepart.syntax',
              'env.lib.python3.5.site-packages.qutepart-3.0.1-py3.5-linux-x86_64.egg.qutepart.indenter',
              'env.lib64.python3.5.site-packages.pip', 'env.lib64.python3.5.site-packages.pip.req',
              'env.lib64.python3.5.site-packages.pip.vcs', 'env.lib64.python3.5.site-packages.pip.utils',
              'env.lib64.python3.5.site-packages.pip.compat', 'env.lib64.python3.5.site-packages.pip.models',
              'env.lib64.python3.5.site-packages.pip._vendor', 'env.lib64.python3.5.site-packages.pip._vendor.distlib',
              'env.lib64.python3.5.site-packages.pip._vendor.distlib._backport',
              'env.lib64.python3.5.site-packages.pip._vendor.colorama',
              'env.lib64.python3.5.site-packages.pip._vendor.html5lib',
              'env.lib64.python3.5.site-packages.pip._vendor.html5lib.trie',
              'env.lib64.python3.5.site-packages.pip._vendor.html5lib.filters',
              'env.lib64.python3.5.site-packages.pip._vendor.html5lib.serializer',
              'env.lib64.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib64.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib64.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib64.python3.5.site-packages.pip._vendor.lockfile',
              'env.lib64.python3.5.site-packages.pip._vendor.progress',
              'env.lib64.python3.5.site-packages.pip._vendor.requests',
              'env.lib64.python3.5.site-packages.pip._vendor.requests.packages',
              'env.lib64.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'env.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'env.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.lib64.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib64.python3.5.site-packages.pip._vendor.packaging',
              'env.lib64.python3.5.site-packages.pip._vendor.cachecontrol',
              'env.lib64.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib64.python3.5.site-packages.pip._vendor.pkg_resources',
              'env.lib64.python3.5.site-packages.pip.commands', 'env.lib64.python3.5.site-packages.pip.operations',
              'env.lib64.python3.5.site-packages.enki', 'env.lib64.python3.5.site-packages.enki.lib',
              'env.lib64.python3.5.site-packages.enki.core', 'env.lib64.python3.5.site-packages.enki.plugins',
              'env.lib64.python3.5.site-packages.enki.plugins.lint',
              'env.lib64.python3.5.site-packages.enki.plugins.repl',
              'env.lib64.python3.5.site-packages.enki.plugins.preview',
              'env.lib64.python3.5.site-packages.enki.plugins.helpmenu',
              'env.lib64.python3.5.site-packages.enki.plugins.vimtutor',
              'env.lib64.python3.5.site-packages.enki.plugins.fuzzyopen',
              'env.lib64.python3.5.site-packages.enki.plugins.navigator',
              'env.lib64.python3.5.site-packages.enki.plugins.appshortcuts',
              'env.lib64.python3.5.site-packages.enki.plugins.editortoolbar',
              'env.lib64.python3.5.site-packages.enki.plugins.qpartsettings',
              'env.lib64.python3.5.site-packages.enki.plugins.searchreplace',
              'env.lib64.python3.5.site-packages.enki.widgets', 'env.lib64.python3.5.site-packages.enki.resources',
              'env.lib64.python3.5.site-packages.PyQt5', 'env.lib64.python3.5.site-packages.PyQt5.uic',
              'env.lib64.python3.5.site-packages.PyQt5.uic.Loader',
              'env.lib64.python3.5.site-packages.PyQt5.uic.port_v2',
              'env.lib64.python3.5.site-packages.PyQt5.uic.port_v3',
              'env.lib64.python3.5.site-packages.PyQt5.uic.Compiler', 'env.lib64.python3.5.site-packages.qutepart',
              'env.lib64.python3.5.site-packages.qutepart.syntax',
              'env.lib64.python3.5.site-packages.qutepart.indenter',
              'env.lib64.python3.5.site-packages.qutepart-3.0.1-py3.5-linux-x86_64.egg.qutepart',
              'env.lib64.python3.5.site-packages.qutepart-3.0.1-py3.5-linux-x86_64.egg.qutepart.syntax',
              'env.lib64.python3.5.site-packages.qutepart-3.0.1-py3.5-linux-x86_64.egg.qutepart.indenter', 'ppedit',
              'ppedit.gui', 'ppedit.tools'],
    url='ppedit.net',
    license='MIT',
    author='Tamás Szelei',
    author_email='szelei.t@gmail.com',
    description='ppedit is a novel editor that helps with developing C++ preprocessor meta-programs.'
)
